{"uuid": "8f379ff9-b8b3-4668-ae56-610233cee628", "children": ["1d9d9efd-4621-4bd1-9622-7d4a16b30c4b", "1d9d9efd-4621-4bd1-9622-7d4a16b30c4b"], "befores": [{"name": "database_base_configuration", "status": "broken", "statusDetails": {"message": "pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on '10.66.8.200' ([WinError 10065] 套接字操作尝试一个无法连接的主机。)\")\n", "trace": "  File \"c:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 957, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 787, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"E:\\automatic\\ui-automatic\\test_cases\\test_device_management\\test_modify_device\\conftest.py\", line 59, in database_base_configuration\n    delete_database_data_test_ci()\n  File \"c:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"E:\\automatic\\ui-automatic\\Utils\\operateDatabaseData.py\", line 31, in delete_database_data_test_ci\n    db=db_name)\n  File \"c:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\pymysql\\__init__.py\", line 94, in Connect\n    return Connection(*args, **kwargs)\n  File \"c:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\pymysql\\connections.py\", line 325, in __init__\n    self.connect()\n  File \"c:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\pymysql\\connections.py\", line 630, in connect\n    raise exc\n"}, "steps": [{"name": "清空数据库", "status": "broken", "statusDetails": {"message": "pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on '10.66.8.200' ([WinError 10065] 套接字操作尝试一个无法连接的主机。)\")\n", "trace": "  File \"c:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"E:\\automatic\\ui-automatic\\Utils\\operateDatabaseData.py\", line 31, in delete_database_data_test_ci\n    db=db_name)\n  File \"c:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\pymysql\\__init__.py\", line 94, in Connect\n    return Connection(*args, **kwargs)\n  File \"c:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\pymysql\\connections.py\", line 325, in __init__\n    self.connect()\n  File \"c:\\users\\keda\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\pymysql\\connections.py\", line 630, in connect\n    raise exc\n"}, "start": 1578028788486, "stop": 1578028788502}], "start": 1578028788486, "stop": 1578028788502}], "start": 1578028788486, "stop": 1578028788564}